name: TagTool Build

on:
  push:
    branches: 
      - dev
      - master

jobs:
  build-branch:
    env:
      TARGET_FRAMEWORK: net8.0-windows
      PLATFORM: x64

    strategy:
      matrix:
        BUILD_CONFIGURATION: [ Debug, Release ]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Submodules 
      uses: snickerbockers/submodules-init@v4

    - name: Determine Version
      id: determine_version
      run: |
        $version = (git rev-parse --short=7 HEAD).Trim()
        echo "Version determined: $version"
        echo "version=$version" >> $GITHUB_ENV

    - name: Install 7Zip
      run: |
        Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z1900-x64.msi" -OutFile "$env:TEMP\7z.msi"
        Start-Process -Wait -FilePath msiexec -ArgumentList "/i", "$env:TEMP\7z.msi", "/quiet" 

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore Packages
      run: nuget restore TagTool.sln

    - name: Build solution
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild TagTool.sln /t:rebuild /p:Platform=${{ env.PLATFORM }} /p:Configuration=${{ matrix.BUILD_CONFIGURATION }} /p:TargetFramework=${{ env.TARGET_FRAMEWORK }}

    - name: Zip Release
      run: |
        & "C:\Program Files\7-Zip\7z.exe" a ${{ matrix.BUILD_CONFIGURATION }}_${{ env.PLATFORM }}.7z ./TagTool/bin/${{ env.PLATFORM }}/${{ matrix.BUILD_CONFIGURATION }}/${{ env.TARGET_FRAMEWORK }}*

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.BUILD_CONFIGURATION }}_${{ env.PLATFORM }}_${{ github.ref_name }}.7z
        path: ${{ matrix.BUILD_CONFIGURATION }}_${{ env.PLATFORM }}.7z

  create-release:
    needs: build-branch
    runs-on: windows-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Create Combined Release
      run: |
        mkdir release
        mv artifacts/* release/
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/*
        tag_name: ${{ steps.determine_version.outputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
